[package]
name = "vulkan-tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = {version = "0.37.3", features = ["linked"]}
log = "0.4.21"
pretty_env_logger = "0.5.0"
winit = "0.29.15"
